### ISSUE TITLE
Wheat Doesn't Work In The Grindstone

### ISSUE THREAD

**Issue by ghost** [McJty/AquaMunda#26] opened 2018-09-04 02:37 UTC
Aqua Munda Version 1.12-0.4.0-beta

When using the grindstone, I was expecting to put wheat in it and be able to grind it into flour. 
I can place the wheat, however the grindstone will not let me grind it. I get the error message "You cannot gind this" I tested this in single player, in a fresh instance with only Aqua Munda, forge & JEI (plus dependencies)

**Comment by njtxus** [comment] 2018-09-08 02:21
i have the same problem. no grindstone recipes seem to work.

**Comment by barrowisp** [comment] 2019-03-08 06:02
I haven't succeeded yet in grinding wheat or sugar canes with the grindstone.  But I'm delighted by results with blaze rods, bone, gravel, and glowstone.
![bs](https://user-images.githubusercontent.com/47377677/54015177-cd005780-4133-11e9-93f4-58ce04124a2c.png)
![gs](https://user-images.githubusercontent.com/47377677/54015178-cd005780-4133-11e9-9ee1-fe60a8ccf7b6.png)

**Comment by barrowisp** [comment] 2019-03-11 07:01
Hi @McJty,

It seems that the reason the grindstone doesn't work on sugar is that your file uses the Bedrock ID (minecraft:reeds) instead of Java ID (minecraft:sugar_cane).  See [https://minecraft.gamepedia.com/Sugar_Cane#Data_values](https://minecraft.gamepedia.com/Sugar_Cane#Data_values).

I could certainly be wrong, but I think that line 75 of
AquaMunda/src/main/java/mcjty/aquamunda/config/GeneralConfiguration.java
should change from
`            addRecipe(cfg, "sugar", new ItemStack(Items.REEDS), new ItemStack(Items.SUGAR, 2), 100);`
to
`            addRecipe(cfg, "sugar", new ItemStack(Items.SUGAR_CANE), new ItemStack(Items.SUGAR, 2), 100);`

**Comment by freelancerleno** [comment] 2019-03-27 19:54
Hi!
I have exactly the same problem.
However, I noticed (I don't know if it's related to the ID problem) when Minecraft only has Forge + McJtyLib + Immersive Craft + Aqua Munda, the flour craft works.
But, if we add even one mod to this list, the flour craft no longer works. I tested with about fifty mods of a different nature independently (tweaks, food mods, technical mods, ...) with the same behaviour.
Seems Aqua Munda doesn't like any other mods :)

**Comment by McJty** [comment] 2019-04-17 06:28
> Hi @McJty,
> 
> It seems that the reason the grindstone doesn't work on sugar is that your file uses the Bedrock ID (minecraft:reeds) instead of Java ID (minecraft:sugar_cane). See https://minecraft.gamepedia.com/Sugar_Cane#Data_values.
> 
> I could certainly be wrong, but I think that line 75 of
> AquaMunda/src/main/java/mcjty/aquamunda/config/GeneralConfiguration.java
> should change from
> ` addRecipe(cfg, "sugar", new ItemStack(Items.REEDS), new ItemStack(Items.SUGAR, 2), 100);`
> to
> ` addRecipe(cfg, "sugar", new ItemStack(Items.SUGAR_CANE), new ItemStack(Items.SUGAR, 2), 100);`

The java edition doesn't have Items.SUGAR_CANE. It is Items.REEDS in java.

**Comment by McJty** [comment] 2019-04-17 06:34
I can reproduce the problem though. I will investigate now

**Comment by McJty** [comment] 2019-04-17 06:48
Found the problem. Will be fixed in next release

**Closed as completed by McJty** 2019-04-17 06:48 UTC
